services:
  server:
    build: ./server
    container_name: messager_server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - server_data:/data
    environment:
      - DATABASE_URL=sqlite:////data/messenger.db
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

#   server_2:
#     build: ./server
#     container_name: messager_server_2
#     ports:
#       - "8002:8000"
#     volumes:
#       - ./server:/app
#       - server_data_2:/data
#     environment:
#       - DATABASE_URL=sqlite:////data/messenger.db
#       - SMTP_HOST=${SMTP_HOST}
#       - SMTP_PORT=${SMTP_PORT}
#       - SMTP_USER=${SMTP_USER}
#       - SMTP_PASS=${SMTP_PASS}
#     command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  client:
    build: ./client
    container_name: messager_client
    ports:
      - "3001:3001"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host

volumes:
  server_data:
#   server_data_2:
